security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_BUREAU, ROLE_VP_SOCIAL, ROLE_MEMBRE, ROLE_USER]
        ROLE_ADMIN:       [ROLE_USER]
        ROLE_BUREAU:      [ROLE_USER]
        ROLE_VP_SOCIAL:   [ROLE_USER]
        ROLE_MEMBRE:      [ROLE_USER]

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: security_login
                check_path: security_login
                username_parameter: email
                password_parameter: password
            logout:
                path: security_logout
                target: security_login

    access_control:
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/assets, roles: PUBLIC_ACCESS }
        - { path: ^/build, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            # Password hashers are resource-intensive by design to ensure security.
            # In tests, it's safe to reduce their cost to improve performance.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
