<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260302232354 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(255) NOT NULL, categorie VARCHAR(100) NOT NULL, filename VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, uploaded_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D8698A76A2B28FE8 ON document (uploaded_by_id)');
        $this->addSql('CREATE TABLE event_photo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, filename VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, evenement_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_55AC3534FD02F13 ON event_photo (evenement_id)');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A76A2B28FE8 FOREIGN KEY (uploaded_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event_photo ADD CONSTRAINT FK_55AC3534FD02F13 FOREIGN KEY (evenement_id) REFERENCES evenement (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE membre ADD profession VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE membre ADD secteur_activite VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ALTER must_change_password DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE document DROP CONSTRAINT FK_D8698A76A2B28FE8');
        $this->addSql('ALTER TABLE event_photo DROP CONSTRAINT FK_55AC3534FD02F13');
        $this->addSql('DROP TABLE document');
        $this->addSql('DROP TABLE event_photo');
        $this->addSql('ALTER TABLE membre DROP profession');
        $this->addSql('ALTER TABLE membre DROP secteur_activite');
        $this->addSql('ALTER TABLE "user" ALTER must_change_password SET DEFAULT false');
    }
}
