<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260225164917 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE annonce (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(255) NOT NULL, contenu TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_active BOOLEAN NOT NULL, auteur_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F65593E560BB6FE6 ON annonce (auteur_id)');
        $this->addSql('CREATE TABLE evenement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, date_debut TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_fin TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, lieu VARCHAR(255) DEFAULT NULL, type VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE log_action (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(255) NOT NULL, entity_name VARCHAR(100) DEFAULT NULL, entity_id INT DEFAULT NULL, details TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5236DF30A76ED395 ON log_action (user_id)');
        $this->addSql('CREATE TABLE mandat (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, poste VARCHAR(100) NOT NULL, date_debut DATE NOT NULL, date_fin DATE DEFAULT NULL, statut VARCHAR(20) NOT NULL, membre_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1E53EFD56A99F74A ON mandat (membre_id)');
        $this->addSql('CREATE TABLE proces_verbal (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, contenu TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, evenement_id INT NOT NULL, redacteur_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5B95250BFD02F13 ON proces_verbal (evenement_id)');
        $this->addSql('CREATE INDEX IDX_5B95250B764D0490 ON proces_verbal (redacteur_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE annonce ADD CONSTRAINT FK_F65593E560BB6FE6 FOREIGN KEY (auteur_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE log_action ADD CONSTRAINT FK_5236DF30A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE mandat ADD CONSTRAINT FK_1E53EFD56A99F74A FOREIGN KEY (membre_id) REFERENCES membre (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE proces_verbal ADD CONSTRAINT FK_5B95250BFD02F13 FOREIGN KEY (evenement_id) REFERENCES evenement (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE proces_verbal ADD CONSTRAINT FK_5B95250B764D0490 FOREIGN KEY (redacteur_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE cas_social DROP CONSTRAINT fk_cas_social_declared');
        $this->addSql('ALTER TABLE cas_social DROP CONSTRAINT fk_cas_social_validated');
        $this->addSql('ALTER TABLE cas_social ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE cas_social ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE cas_social ALTER type SET NOT NULL');
        $this->addSql('ALTER TABLE cas_social ALTER statut_assistance DROP DEFAULT');
        $this->addSql('ALTER TABLE cas_social ADD CONSTRAINT FK_A5A30DEBC48B85B0 FOREIGN KEY (declared_by_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE cas_social ADD CONSTRAINT FK_A5A30DEBC69DE5E5 FOREIGN KEY (validated_by_id) REFERENCES "user" (id)');
        $this->addSql('ALTER INDEX idx_cas_social_membre RENAME TO IDX_A5A30DEB6A99F74A');
        $this->addSql('ALTER TABLE cotisation ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE cotisation ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE cotisation ALTER type DROP DEFAULT');
        $this->addSql('ALTER TABLE cotisation ALTER montant DROP DEFAULT');
        $this->addSql('ALTER TABLE cotisation ALTER statut DROP DEFAULT');
        $this->addSql('ALTER TABLE cotisation ADD CONSTRAINT FK_AE64D2ED398776CB FOREIGN KEY (cas_social_id) REFERENCES cas_social (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER INDEX uniq_recu_numero RENAME TO UNIQ_AE64D2EDEA5C6E1C');
        $this->addSql('ALTER INDEX idx_cotisation_membre RENAME TO IDX_AE64D2ED6A99F74A');
        $this->addSql('ALTER INDEX idx_cotisation_cas_social RENAME TO IDX_AE64D2ED398776CB');
        $this->addSql('ALTER TABLE membre ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE membre ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE membre ALTER statut DROP DEFAULT');
        $this->addSql('ALTER TABLE membre ALTER solde_cotisations DROP DEFAULT');
        $this->addSql('ALTER INDEX uniq_membre_identifiant RENAME TO UNIQ_F6B4FB29C90409EC');
        $this->addSql('ALTER TABLE patrimoine ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE patrimoine ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE patrimoine ALTER valeur_achat DROP DEFAULT');
        $this->addSql('ALTER TABLE patrimoine ALTER etat DROP DEFAULT');
        $this->addSql('ALTER TABLE projet ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE projet ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE projet ALTER budget_total DROP DEFAULT');
        $this->addSql('ALTER TABLE projet ALTER montant_collecte DROP DEFAULT');
        $this->addSql('ALTER TABLE projet ALTER benefices DROP DEFAULT');
        $this->addSql('ALTER TABLE projet ALTER statut DROP DEFAULT');
        $this->addSql('ALTER TABLE "user" ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE "user" ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE "user" ALTER roles TYPE JSON USING roles::json');
        $this->addSql('ALTER INDEX uniq_user_email RENAME TO UNIQ_8D93D649E7927C74');
        $this->addSql('ALTER INDEX idx_user_membre RENAME TO IDX_8D93D6496A99F74A');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE annonce DROP CONSTRAINT FK_F65593E560BB6FE6');
        $this->addSql('ALTER TABLE log_action DROP CONSTRAINT FK_5236DF30A76ED395');
        $this->addSql('ALTER TABLE mandat DROP CONSTRAINT FK_1E53EFD56A99F74A');
        $this->addSql('ALTER TABLE proces_verbal DROP CONSTRAINT FK_5B95250BFD02F13');
        $this->addSql('ALTER TABLE proces_verbal DROP CONSTRAINT FK_5B95250B764D0490');
        $this->addSql('DROP TABLE annonce');
        $this->addSql('DROP TABLE evenement');
        $this->addSql('DROP TABLE log_action');
        $this->addSql('DROP TABLE mandat');
        $this->addSql('DROP TABLE proces_verbal');
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('ALTER TABLE cas_social DROP CONSTRAINT FK_A5A30DEBC48B85B0');
        $this->addSql('ALTER TABLE cas_social DROP CONSTRAINT FK_A5A30DEBC69DE5E5');
        $this->addSql('ALTER TABLE cas_social ALTER id SET DEFAULT nextval(\'cas_social_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE cas_social ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE cas_social ALTER type DROP NOT NULL');
        $this->addSql('ALTER TABLE cas_social ALTER statut_assistance SET DEFAULT \'En attente\'');
        $this->addSql('ALTER TABLE cas_social ADD CONSTRAINT fk_cas_social_declared FOREIGN KEY (declared_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cas_social ADD CONSTRAINT fk_cas_social_validated FOREIGN KEY (validated_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX idx_a5a30deb6a99f74a RENAME TO idx_cas_social_membre');
        $this->addSql('ALTER TABLE cotisation DROP CONSTRAINT FK_AE64D2ED398776CB');
        $this->addSql('ALTER TABLE cotisation ALTER id SET DEFAULT nextval(\'cotisation_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE cotisation ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE cotisation ALTER type SET DEFAULT \'mensuelle\'');
        $this->addSql('ALTER TABLE cotisation ALTER montant SET DEFAULT \'0.00\'');
        $this->addSql('ALTER TABLE cotisation ALTER statut SET DEFAULT \'payee\'');
        $this->addSql('ALTER INDEX idx_ae64d2ed398776cb RENAME TO idx_cotisation_cas_social');
        $this->addSql('ALTER INDEX uniq_ae64d2edea5c6e1c RENAME TO uniq_recu_numero');
        $this->addSql('ALTER INDEX idx_ae64d2ed6a99f74a RENAME TO idx_cotisation_membre');
        $this->addSql('ALTER TABLE membre ALTER id SET DEFAULT nextval(\'membre_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE membre ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE membre ALTER statut SET DEFAULT \'Actif\'');
        $this->addSql('ALTER TABLE membre ALTER solde_cotisations SET DEFAULT \'0.00\'');
        $this->addSql('ALTER INDEX uniq_f6b4fb29c90409ec RENAME TO uniq_membre_identifiant');
        $this->addSql('ALTER TABLE patrimoine ALTER id SET DEFAULT nextval(\'patrimoine_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE patrimoine ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE patrimoine ALTER valeur_achat SET DEFAULT \'0.00\'');
        $this->addSql('ALTER TABLE patrimoine ALTER etat SET DEFAULT \'Bon état\'');
        $this->addSql('ALTER TABLE projet ALTER id SET DEFAULT nextval(\'projet_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE projet ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE projet ALTER budget_total SET DEFAULT \'0.00\'');
        $this->addSql('ALTER TABLE projet ALTER montant_collecte SET DEFAULT \'0.00\'');
        $this->addSql('ALTER TABLE projet ALTER benefices SET DEFAULT \'0.00\'');
        $this->addSql('ALTER TABLE projet ALTER statut SET DEFAULT \'En cours\'');
        $this->addSql('ALTER TABLE "user" ALTER id SET DEFAULT nextval(\'user_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE "user" ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE "user" ALTER roles TYPE TEXT');
        $this->addSql('ALTER INDEX idx_8d93d6496a99f74a RENAME TO idx_user_membre');
        $this->addSql('ALTER INDEX uniq_8d93d649e7927c74 RENAME TO uniq_user_email');
    }
}
